name: dash

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check-dash:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      # taken from here: https://github.com/eclipse/dash-licenses#example-python
      - name: Create Dash Dependency Report
        run: |
          python3 -m venv ./.venv/kuksa-client
          source ./.venv/kuksa-client/bin/activate

          pip install --upgrade pip
          pip install -r kuksa-client/requirements.txt

          deactivate

          python3 -m venv ./.venv/pipdeptree
          source ./.venv/pipdeptree/bin/activate

          pip install pipdeptree
          pipdeptree -a -f --python ./.venv/kuksa-client/bin/python \
          | sed -E -e 's|([^= ]+)==([^= ]+)|pypi/pypi/-/\1/\2|' -e 's| ||g' \
          | sort | uniq \
          > dependencies.txt

      - name: Dash license check
        uses: eclipse-kuksa/kuksa-actions/check-dash@2
        with:
          dashinput: ${{github.workspace}}/dependencies.txt
