name: Generate and upload SBOM into sbom.eclipse.org

on:
  push:
    branches:
      - "main"
    paths:
      - "kuksa-client/pyproject.toml"
      - "kuksa-client/requirements.txt"
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        default: 'main'
        required: true

env:
  PYTHON_VERSION: '3.12'
  PRODUCT_PATH: './kuksa-client'
  PLUGIN_VERSION: '5.1.1'

permissions:
  contents: read

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: ${{ github.event.inputs.version }}

      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install cyclonedx-py
        run: pipx install cyclonedx-bom==${{ env.PLUGIN_VERSION }}

      - name: Extract product version
        id: version
        run: |
          # Triggered by tag push
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            VERSION="${GITHUB_REF#refs/tags/}"
          # Triggered by push to deps files
          elif [[ "$GITHUB_EVENT_NAME" == "push" ]]; then
            VERSION="latest"
          # Manual trigger
          else
            VERSION="${{ github.event.inputs.version }}"
          fi
          echo "PROJECT_VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Product version: $VERSION"

      - name: Generate sbom
        run: cyclonedx-py requirements ${{ env.PRODUCT_PATH }}/requirements.txt -o bom.json

      - name: Upload sbom
        uses: eclipse-csi/workflows/upload-sbom@20e3c63807b2bd61b7f1a9f438e5ce588c054efc # main
        with:
          sbom-file: bom.json
          product-name: 'kuksa-python-sdk'
          product-version: ${{ steps.version.outputs.PROJECT_VERSION }}
